### ISSUE TITLE
`xbin -d` should fail for bad download suffix

### ISSUE THREAD

**Issue by sberan** [calebboyd/xbin#14]
`echo 'console.log("hello")' | xbin -d bad-suffix` creates an executable out of the github 404 page. It should instead fail with an error message that the binary isn't found.

**Comment by calebboyd** [comment]
Good idea, fixed in 84a634727051d44323f554326e2d2ce6d1f8b10a
i mean 8e9d71096ab628d75eff370a4e02df14250dc786...

**Comment by sberan** [comment]
Thanks! 🎉

**Comment by calebboyd** [comment]
I switched to status code. on npm @ 2.2.0

**Comment by sberan** [comment]
🥇
