### ISSUE TITLE
add a design document

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [calebboyd/xbin#3]

**Comment by calebboyd** [comment]
Can you elaborate more on this request?

**Comment by rahul-dutt-sharma** [comment]
high level design of how the process and code logic works

**Comment by calebboyd** [comment]
That's a good idea,  -- something that would be more helpful to contributors.

**Comment by rahul-dutt-sharma** [comment]
Yes!.

**Comment by calebboyd** [comment]
I'll start it here

## How it works

xbin is built around a series of [middleware](https://github.com/calebboyd/app-builder). Each middleware function is described below. The first point will describe the upstream function and the second, its downstream function.
- **cli** 
  - Collects and normalizes input
  - Writes and noramlizes output
- **download**
  - Downloads the Node Source if not present in the configured or default storage location
  - Nothing
- **compile**
  - Adds an additional source file to node source `_third_party_main.js`. This file contains code that is responsible for loading your application bundle
  - Executes the node build process with parameters provided to `xbin`
- **artifacts**
  - Creates a temporary `xbin` directory in the node source folder. If the temp directory already exists, it repopulates the node source with the versions stored in the temporary directory
  - Stores original node source files before they're overwritten, and then writes their patched versions and adds new files.
- **nodegyp**
  - Nothing
  - Appends any additional source files setup during the other middleware or plugin phases and records them in the node.gyp manifest
- **flags**
  - Nothing
  - If any v8 flags `--flag` are passed to xbin. The flag is compiled with the node runtime. These options also exist in the node.gyp file.
- **argv**
  - Updates `src/node.cc` of the Node Source, to bypass strict argv options. Allowing you to pass arbitrary command line options to your custom runtime.
- **resource**
  - If resource flags are supplied, additional code is added that builds a dictionary of getters keyed by resource basename. The getters return a Buffer of the resource's bytes. They are retrieved at runtime by reading from `fs.readFile` and `fs.readFileSync` 
    - eg. `cat input.js | xbin --resource ./some/file > out.run` will cause any `readFile` or `readFileSync` of `./any/path/file` where the basename is `file` to retrieve the embedded resource.
- **ico**
  - Overwrites node's included icon file

Plugins act as additional middleware appended after the ones described here

### Compiler

The Compiler object that is passed to each middleware function has _all_ of the xbin configuration properties (options) appended to it. Additionally it has these relevant methods
- `readFileAsync('node/src/file'): Promise<{ filename: string, contents: Buffer }>` - The file path should _not_ be normalized, or be prefaced with a `/`.  The filename will be joined and normalized with the temporary source locatoin. Files that are read into the compiler cache are written out during the `articacts` downstream function
- `writeFileAsync('node/src/file'): Promise<void>` - This method immediately writes a file to the node source directory currently being operated on.
- `files: Array<{ filename: string, contents: Buffer }>`  - This property stores currently cached files.
