### ISSUE TITLE
process.dlopen(module, path) error

### ISSUE THREAD

**Issue by unbalanced** [calebboyd/xbin#4]
Hey, overall great project!
I'm currently assessing using it and contributing further features that i will need. 

Currently the function process.dlopen(module, path)
Is returning "Error: %1 is not a valid Win32 application"  on a test project that i have setup

Any idea why is that happening?
Many thanks and good luck

**Comment by calebboyd** [comment]
Hi Amir! Thanks! That error is shown when the DLL you're loading is built against a different architecture than the version of node that is loading it. You can find out what architecture is used in either of your node versions by checking `process.arch`. Then you just need to match them up. You can inspect the node build scripts to see what the appropriate flags for your desired architecture might be, and then apply them to your xbin command. I'll see if I can make a note of this.

**Comment by unbalanced** [comment]
Thanks for the fast response.
When i run my compiled exe (that generates the above error) i see the process.arch is ia32
When i run the app without building i see x64
how do i pass the flag to use x64?

-flag --target_arch=x64
?

**Comment by calebboyd** [comment]
Are you using windows?

If you are the argument can be found here
https://github.com/nodejs/node/blob/master/vcbuild.bat#L50

windows: `xbin --make x64`
linux: `xbin --configure="--dest-cpu=x64"`

**Comment by unbalanced** [comment]
Thanks, now process.dlopen(module, path) gives another error:
"Error: Module version mismatch. Expected 46, got 48."
:)

**Comment by calebboyd** [comment]
Are you setting `--version`? --the version you build to consume the native module will need to be the same as the version that built the native module.

**Comment by unbalanced** [comment]
yep i found it as well and build and it finally WORKED!
Many thanks for your help @calebboyd.

**Comment by calebboyd** [comment]
🙇
