### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by unbalanced** [calebboyd/xbin#5]
Tried to build the example project. Though the webpack bundle fails:

ERROR in ./~/heapdump/lib/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Debug/addon

Furthermore, i'm not sure, but doesn't the build command suppose to use xbin cmd instead of node?
"build": "node ../index -i ./build/native-test.js -o ./out.exe",

**Comment by calebboyd** [comment]
Ahh yeah, I'll add an `IgnorePlugin` for the debug file which should curb that error.
- [x] add IgnorePlugin to native example
