### ISSUE TITLE
overriding the node.rc configs 

### ISSUE THREAD

**Issue by unbalanced** [calebboyd/xbin#8]
Do you know if is possible to override the [node.rc](https://github.com/nodejs/node/blob/4896f0f6103154da355606653606bc79b0f8f01d/src/res/node.rc) file in order to be able to use a custom icon, CompanyName, FileDescription, etc.

Thanks :)

**Comment by unbalanced** [comment]
update: after reading the code i realized there's a way to override the icon via the programmatic API 
```
build({
    ico: './assets/myapp.ico',
...
})
```

But could not find a way to override the rest of the details.
If it's not possible, let me know how you think it should be solved and i'll try to create a pull request.

Thanks

**Comment by calebboyd** [comment]
Hi Amir, Sorry for the poor documentation. 
The project will eventually support plugins, but I agree `node.rc` controls should be added.

I'd love to get your feedback on this interface

```
$ npm i xbin-rc
```
This would download an `xbin-rc` package from npm  (sub package in this repo) and add it to the directory. It would then be executed by doing

`xbin -i input.js -o out.exe --plugin-rc opts`

It would essentially look like the following

```javascript
export default async function xbinRc (compiler, next) {
    const options = compiler.plugins.rc
    if (badOptions(options)) { return next() }
    const rc = await compiler.readFileAsync('src/res/node.rc')
    rc.contents = rc.contents
      .replace(...., options.asdf)
      .replace(...., options..qwer)
      ....
  return next()
}

```

I'd accept a PR that doesn't do plugins yet but adds this option via `--plugin-rc`

**Comment by unbalanced** [comment]
Thanks for the fast response.

So do you want me to add it as a middleware in the mean time? Like the ico middleware?

**Comment by calebboyd** [comment]
That would be great!
